# Generated by Django 6.0.4 on 2026-04-09 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active_nodes', models.PositiveIntegerField(default=0)),
                ('total_logs_ingested', models.BigIntegerField(default=0)),
                ('threats_detected', models.PositiveIntegerField(default=0)),
                ('global_model_accuracy', models.FloatField(default=0.0)),
                ('avg_privacy_epsilon', models.FloatField(default=0.0)),
                ('avg_inference_latency_ms', models.FloatField(default=0.0)),
                ('active_training_rounds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Platform metrics',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('django', 'Django Application'), ('elasticsearch', 'Elasticsearch'), ('aggregator', 'FL Aggregator'), ('database', 'Database'), ('redis', 'Redis / Message Broker')], max_length=20)),
                ('is_healthy', models.BooleanField(default=True)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System health checks',
                'ordering': ['-checked_at'],
            },
        ),
    ]
