# Generated by Django 6.0.4 on 2026-04-09 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updates_received', models.PositiveIntegerField(default=0)),
                ('updates_accepted', models.PositiveIntegerField(default=0)),
                ('updates_rejected', models.PositiveIntegerField(default=0)),
                ('total_samples', models.PositiveIntegerField(default=0)),
                ('aggregation_time_seconds', models.FloatField(default=0.0)),
                ('global_model_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FederatedNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('host', models.GenericIPAddressField(help_text='Node container IP or hostname')),
                ('port', models.PositiveIntegerField(default=8081)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('training', 'Training'), ('syncing', 'Syncing'), ('error', 'Error')], default='offline', max_length=20)),
                ('cpu_cores', models.PositiveSmallIntegerField(default=4)),
                ('memory_gb', models.FloatField(default=8.0)),
                ('gpu_available', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('total_samples', models.PositiveIntegerField(default=0, help_text='Number of local training samples')),
                ('latitude', models.FloatField(blank=True, help_text='Geographic latitude', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Geographic longitude', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradientUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_accuracy', models.FloatField(default=0.0)),
                ('local_loss', models.FloatField(default=0.0)),
                ('num_samples', models.PositiveIntegerField(default=0)),
                ('update_size_bytes', models.BigIntegerField(default=0)),
                ('update_path', models.CharField(blank=True, help_text='Path or URI to the serialized gradient tensor', max_length=500)),
                ('epsilon_spent', models.FloatField(default=0.0, help_text='Privacy budget consumed in this update')),
                ('accepted', models.BooleanField(default=False, help_text='Whether the aggregator accepted this update')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epsilon', models.FloatField(default=1.0, help_text='Current cumulative epsilon (privacy loss parameter)')),
                ('delta', models.FloatField(default=1e-05, help_text='Delta parameter for (ε, δ)-differential privacy')),
                ('max_epsilon', models.FloatField(default=10.0, help_text='Maximum allowed cumulative epsilon before halting')),
                ('noise_multiplier', models.FloatField(default=1.1, help_text='Gaussian noise multiplier applied to gradients')),
                ('clip_norm', models.FloatField(default=1.0, help_text='Gradient clipping L2 norm bound')),
                ('rounds_consumed', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('aggregating', 'Aggregating'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('global_accuracy', models.FloatField(blank=True, null=True)),
                ('global_loss', models.FloatField(blank=True, null=True)),
                ('aggregation_strategy', models.CharField(default='fedavg', help_text='Aggregation algorithm (fedavg, fedprox, scaffold)', max_length=30)),
                ('min_nodes_required', models.PositiveSmallIntegerField(default=2)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-round_number'],
            },
        ),
    ]
