# Generated by Django 6.0.4 on 2026-04-09 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('federated', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federatednode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='users.organization'),
        ),
        migrations.AddField(
            model_name='gradientupdate',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradient_updates', to='federated.federatednode'),
        ),
        migrations.AddField(
            model_name='privacybudget',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_budgets', to='federated.federatednode'),
        ),
        migrations.AddField(
            model_name='traininground',
            name='participating_nodes',
            field=models.ManyToManyField(blank=True, related_name='training_rounds', to='federated.federatednode'),
        ),
        migrations.AddField(
            model_name='gradientupdate',
            name='training_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradient_updates', to='federated.traininground'),
        ),
        migrations.AddField(
            model_name='aggregationlog',
            name='training_round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregation_log', to='federated.traininground'),
        ),
        migrations.AlterUniqueTogether(
            name='gradientupdate',
            unique_together={('training_round', 'node')},
        ),
    ]
