# Generated by Django 6.0.4 on 2026-04-09 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('federated', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('firewall', 'Firewall'), ('ids', 'Intrusion Detection System'), ('endpoint', 'Endpoint Agent'), ('cloud', 'Cloud Service'), ('auth', 'Authentication Service'), ('dns', 'DNS Server'), ('proxy', 'Web Proxy'), ('custom', 'Custom Source')], max_length=20)),
                ('host', models.GenericIPAddressField(help_text='IP address of the log source')),
                ('port', models.PositiveIntegerField(default=514)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('tls', 'TLS')], default='tcp', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sources', to='federated.federatednode')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('host', 'port', 'node')},
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ingesting', 'Ingesting'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('byte_size', models.BigIntegerField(default=0, help_text='Total payload size in bytes')),
                ('elasticsearch_index', models.CharField(blank=True, help_text='Target ES index name (e.g., siem-logs-2026.04)', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='logs.logsource')),
            ],
            options={
                'verbose_name_plural': 'Ingestion batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SIEMLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(help_text='Original event timestamp from source')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('raw_hash', models.CharField(help_text='SHA-256 hash of the raw log line', max_length=64)),
                ('parsed_fields', models.JSONField(blank=True, default=dict)),
                ('threat_score', models.FloatField(blank=True, help_text='Score assigned by the threat detection model (0.0 – 1.0)', null=True)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='logs.ingestionbatch')),
            ],
            options={
                'verbose_name': 'SIEM log entry',
                'verbose_name_plural': 'SIEM log entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
