# Generated by Django 6.0.4 on 2026-04-09 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rule_type', models.CharField(choices=[('sigma', 'Sigma Rule'), ('yara', 'YARA Rule'), ('custom', 'Custom ML Rule')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('logic', models.TextField(help_text='Rule definition body (Sigma YAML, YARA syntax, or JSON)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-hits'],
            },
        ),
        migrations.CreateModel(
            name='IOCEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ioc_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('md5', 'MD5 Hash'), ('sha256', 'SHA-256 Hash'), ('email', 'Email Address'), ('cve', 'CVE Identifier')], max_length=10)),
                ('value', models.CharField(db_index=True, max_length=500)),
                ('enrichment_score', models.FloatField(default=0.0, help_text='Threat enrichment score from the global model (0.0 – 1.0)')),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence level (0.0 – 1.0)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('source_feeds', models.JSONField(blank=True, default=list, help_text='List of intel feed names that reported this IOC')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'IOC entry',
                'verbose_name_plural': 'IOC entries',
                'ordering': ['-enrichment_score'],
            },
        ),
        migrations.CreateModel(
            name='ThreatModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('architecture', models.CharField(help_text='Model architecture identifier (e.g., transformer-v2, lstm-attention)', max_length=50)),
                ('status', models.CharField(choices=[('training', 'Training'), ('validating', 'Validating'), ('deployed', 'Deployed'), ('retired', 'Retired')], default='training', max_length=20)),
                ('accuracy', models.FloatField(default=0.0, help_text='Validation accuracy (0.0 – 1.0)')),
                ('f1_score', models.FloatField(default=0.0)),
                ('false_positive_rate', models.FloatField(default=0.0)),
                ('parameters_path', models.CharField(blank=True, help_text='Path or URI to serialized model weights', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(help_text='Threat probability (0.0 – 1.0)')),
                ('label', models.CharField(blank=True, help_text='Predicted class label (e.g., malware, phishing, benign)', max_length=50)),
                ('inference_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
