# Generated by Django 6.0.4 on 2026-04-09 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('federated', '0002_initial'),
        ('logs', '0001_initial'),
        ('threat_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='threatmodel',
            name='training_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_models', to='federated.traininground'),
        ),
        migrations.AddField(
            model_name='iocentry',
            name='associated_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iocs', to='threat_detection.threatmodel'),
        ),
        migrations.AddField(
            model_name='threatscore',
            name='log_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='logs.siemlogentry'),
        ),
        migrations.AddField(
            model_name='threatscore',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='threat_detection.threatmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='iocentry',
            unique_together={('ioc_type', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='threatscore',
            unique_together={('log_entry', 'model')},
        ),
    ]
